name:                aoc2021-day22
version:             0.1.0.0
github:              "oldfartdeveloper/aoc2021-day22"
license:             BSD3
author:              "Scott Nelson Smith"
maintainer:          "scottnelsonsmith@gmail.com"
copyright:           "Copyright (c) 2021 Scott Smith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oldfartdeveloper/aoc2021-day22#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- ghc >= 8.10.0 && < 9.0
- containers
- split

library:
  source-dirs: src

executables:
  aoc2021-day22-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021-day22
    # Following fixes bug flagged by
    # https://stackoverflow.com/questions/67519851/multiple-files-use-the-same-module-name
    when:
    - condition: false
      other-modules: Paths_aoc2021_day22


tests:
  aoc2021-day22-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021-day22
